backend:
  name: git-gateway
  branch: main

media_folder: "static/images" 
public_folder: "/images"


collections:
  - name: "Services"
    label: "Services" 
    folder: "src/content/services" 
    create: true 
    slug: "{{slug}}" 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "URL", name: "url", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Code", name: "code", widget: "code"}
      - label: "Type"
        name: "type"
        widget: "select"
        options: ["client", "service"]

  - name: "Clients"
    label: "clients" 
    folder: "src/content/services/clients" 
    create: true 
    slug: "{{slug}}" 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "URL", name: "url", widget: "string"}
      - {label: "client-logo", name: "client-logo", widget: "image"}
      - label: "Align Content"
          name: "align"
          widget: "select"
          options: ["client", "service"]